export const workItems = [
  {
    id: 1,
    logo: "/images/work/eskwelabs.jpg",
    company: "Eskwelabs",
    position: "Education Innovation Fellow (Intern)",
    location: "Philippines",
    dates: "Jul 2025 – Present",
    bullets: [
      "Investigated how youth and workforce learners interact with AI tools",
      "Synthesized research findings to inform inclusive curriculum design",
      "Collaborated with regional education leaders across Southeast Asia",
    ],
    tags: ["EdTech", "UX Research", "Curriculum Design"],
  },
  {
    id: 2,
    logo: "/images/work/btt.png",
    company: "Break Through Tech AI",
    position: "AI/ML Fellow",
    location: "Remote",
    dates: "Apr 2025 – Present",
    bullets: [
      "Selected from 3000+ for national AI program focused on social good",
      "Built real-world AI projects using NLP and recommender systems",
      "Earned ML certification from Cornell Tech and practiced responsible AI design",
    ],
    tags: ["Machine Learning", "NLP", "Recommender Systems", "Python"],
  },
  {
    id: 3,
    logo: "/images/work/cwru.avif",
    company: "CWRU Computer Science Department",
    position: "Teaching Assistant for CSDS 233: Data Structures",
    location: "Cleveland, OH",
    dates: "Jan 2025 – Present",
    bullets: [
      "Supported 150+ students in Data Structures as sole first-year TA",
      "Led reviews, graded work, and offered 1:1 academic support",
      "Helped students navigate core CS concepts through structured guidance",
    ],
    tags: ["Teaching", "Python", "CS Education", "Peer Mentorship"],
  },
  {
    id: 4,
    logo: "/images/work/cwru.avif",
    company: "CWRU Career Center",
    position: "Career Consulting Intern – EST Division",
    location: "Cleveland, OH",
    dates: "Nov 2024 – Present",
    bullets: [
      "Designed newsletters reaching 2500+ STEM students across 3 schools",
      "Provided personalized resume and career support to undergrad and grad students",
      "Built connections between students and employers in engineering/science fields",
    ],
    tags: ["Career Coaching", "Content Writing", "STEM Outreach"],
  },
  {
    id: 5,
    logo: "/images/work/beats.svg",
    company: "Beats by Dre",
    position: "Data Analyst Extern – Consumer Insights",
    location: "Remote",
    dates: "Dec 2024 – Feb 2025",
    bullets: [
      "Extracted sentiment insights from product reviews using TextBlob and Gemini AI",
      "Conducted EDA to identify trends in user feedback",
      "Visualized findings to support product and brand strategy",
    ],
    tags: ["NLP", "EDA", "Python", "Consumer Analytics"],
  },
  {
    id: 6,
    logo: "/images/work/fowler.jpg",
    company: "Fowler Center (ThinkImpact Fellowship)",
    position: "ThinkImpact Fellow",
    location: "Iceland / Remote",
    dates: "Sep 2024 – Apr 2025",
    bullets: [
      "Researched circular economy and sustainable business models in Iceland",
      "Collaborated with 11 other fellows through site visits and strategy sessions",
      "Explored social entrepreneurship through systems thinking",
    ],
    tags: ["Sustainability", "Systems Thinking", "Social Impact"],
  },
  {
    id: 7,
    logo: "/images/work/uwcij-chubu.png",
    company: "UWC ISAK Japan",
    position: "Student Researcher – Fish2Meta Project",
    location: "Japan",
    dates: "Oct 2022 – Mar 2024",
    bullets: [
      "Led experiments on cerebellar learning with 40+ participants using prism adaptation",
      "Developed EEG preprocessing pipelines and reproducible workflows",
      "Presented findings through oral and poster presentations at Chubu University",
    ],
    tags: ["EEG", "Python", "Experimental Design", "Neuroscience"],
  }
];
